config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "deals#welcome"
  resources :users
  resources :deals
  resources :orders do
    post :submit, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
	has_many_attached :image
	validates :publish_date, uniqueness: true, presence: true
	validates :price, presence: true
	validates :quantity, presence: true
	validates :title, presence: true
	has_one_attached :image, :dependent => :destroy

	after_save :check_active

	def check_active
		if Time.now >= self.publish_date
			self.update_column("active", true)
		end
		Deal.where.not(id: self.id).update_all(active: false)	
	end

	def check_deal_outstock
		deal_grabbed = OrderDetail.where(deal: self).sum(:quantity)
		if deal_grabbed >= self.quantity
			self.update_column("active", false)
		end
	end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  

  def update_total
    self.sub_total = self.order_details.sum(:total_price)
    self.date_new = DateTime.now
    self.status = "Confirmed"
    discount = calculate_loyalty_discount
    self.discount = discount.nil? ? 0.0 : discount
    self.grand_total = self.sub_total - self.discount # tax and discount can be added
    self.save
  end

  def deal_grabbed(deal)
    user = self.user
    order = user.orders.includes(:order_details).where(order_details: {deal: deal})
  end

  def calculate_loyalty_discount
    user = self.user
    order_count = user.orders.where(status: "Confirmed").count
    if order_count.between?(1, 4)
      discount = self.sub_total * (order_count / 100.0)
    elsif order_count >=5
      discount = self.sub_total * (5 / 100.0)
    end
    discount  
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :deal
  validate :deal_grabbed

  def validate
    deal_grabbed = OrderDetail.where(deal: self.deal).sum(:quantity)
    if self.deal.nil? || deal_grabbed >= self.deal.quantity
      return {message: "Deal Out Of Stock", status: false}
    else
      return {message: "Available", status: true}
    end  
  end

  def update_total
    price = self.deal.discounted_price.present? ? self.deal.discounted_price : self.deal.price
    quantity = 1
    total_price = quantity * price
    self.quantity = quantity
    self.price = price
    self.total_price = total_price
    if self.save
      self.order.update_total
      self.deal.check_deal_outstock
      return true
    else
      return false  
    end
  end

  def deal_grabbed
    order = self.order.deal_grabbed(self.deal)
    result = order.present?
    self.errors.add(:base, 'Already Ordered') if result
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :orders
	enum role: [:admin, :customer]

	def admin?
		self.role == "admin"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	before_action :authenticate_user
	before_action :authorize_user, only: [:new, :create, :edit, :update, :index ]
	before_action :find_deal

	def welcome
		@active_deal = Deal.find_by(active: true)
		@order = @user.orders.includes(:order_details).where(status: 'Confirmed', order_details: {deal: @active_deal}) if @user
	end

	def index
		@deals = Deal.all
	end

	def new
		@deal = Deal.new
	end

	def create
		@deal = Deal.new(deal_params)
		respond_to do |format|
			if @deal.save
				format.html { redirect_to deals_path, notice: 'Deal was Created' }
			else
				format.html { redirect_to new_deal_path, alert: @deal.errors.full_messages.first }
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @deal.update(deal_params)
				format.html { redirect_to deals_path, notice: 'Deal was Created' }
			else
				format.html { redirect_to new_deal_path, alert: @deal.errors.full_messages.first }
			end
		end
	end

	private

	def authenticate_user
		user_id = cookies["login"]
		@user = User.find_by(id: user_id) if user_id
	end

	def authorize_user
		redirect_to root_path if @user.nil? || !@user.admin?
	end

	def find_deal
		@deal = Deal.find(params[:id]) if params[:id]
	end

	def deal_params
    params.require(:deal).permit(:id, :title, :description, :price, :discounted_price, :quantity, :publish_date, :image)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user
	before_action :get_deal
	
	def new
		respond_to do |format|
			format.html
			format.js
		end
	end

	def index
		@orders = @user.orders.where.not(status: 'Open')
	end

	def submit
		order = @user.orders.find_by(status: 'Open')
		order = @user.orders.create(status: 'Open') if order.nil?
		details = order.order_details.build(deal: @deal)
		deal_avbl = details.validate
		if deal_avbl[:status] && details.update_total
			redirect_to orders_path
		else
			respond_to do |format|
				format.js
			end
		end
	end

	private

	def authenticate_user
		user_id = cookies["login"]
		@user = User.find_by(id: user_id) if user_id
		redirect_to root_path if @user.nil?
	end	

	def get_deal
		@deal = Deal.find_by(active: true)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user

	def show
		@user
	end

	private
		def set_user
			@user = User.find_by(id: params[:id])
			set_cookie if @user
		end

		def set_cookie
			cookies[:login] = { value: @user.id, expires: 1.hour }
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/deals/_form.html.haml
.deal_form
  = simple_form_for @deal do |f|
    = flash["alert"]  
    .form-group
      = f.input :title
    .form-group
      = f.label :description
      = f.text_field :description
    .form-group
      = f.input :price
    .form-group
      = f.input :discounted_price
    .form-group
      = f.input :quantity 
    .form-group
      = f.input :publish_date
    %br  
    .form-group
      = f.input :image , as: :file         
    %br
    .form-actions
      = f.button :submit, class: "btn btn-primary btn-block btn-lg"

app/views/deals/_today_deal.html.haml
- if @user.admin?
  %h1.fw-light Admin Logged In
  = link_to "New Deal", new_deal_path
- if @active_deal
  %h1.fw-light Today Deal
  .d-flex.justify-content-center.container.mt-5
  .card.p-3.py-4
    %h5.mb-0=@active_deal.title
    %span.text-black-50.p-description
      = @active_deal.description
      %br/
    - if @active_deal.image.attached?  
      = image_tag @active_deal.image, :style => "height: 130pxwidth: 70px"  
    .d-flex.justify-content-between.align-items-center.mt-4
      %span= "Price :$#{@active_deal.price}"
      %span= "Discounted Price :$#{@active_deal.discounted_price}"
      %button.btn.btn-dark.btn-sm{:type => "button"}
        - if @order.present?
          = "ORDERED"
        - else  
          = link_to 'GRAB DEAL', new_order_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}

  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
- else
  %h1.fw-light Today Deal Is Out Of Stock

app/views/deals/edit.html.haml
.row
  .col-sm-12.col-sm-offset-3
    %h1.text-center Edit Deal
    = render partial: 'form'

app/views/deals/index.html.haml

%table.table
  %thead
    %tr
      %th{:scope => "col"} Edit
      %th{:scope => "col"} Title
      %th{:scope => "col"} Description
      %th{:scope => "col"} Price
      %th{:scope => "col"} Discounted Price
      %th{:scope => "col"} Quantity
      %th{:scope => "col"} Publish Date
      %th{:scope => "col"} Active
      %th{:scope => "col"} Image
  %tbody
    - @deals.each do |deal|
      %tr
        %th{:scope => "row"}= link_to "Edit Deal", edit_deal_path(deal)
        %th{:scope => "row"}= deal.title
        %td= deal.description
        %td= deal.price
        %td= deal.discounted_price
        %td= deal.quantity
        %td= deal.publish_date
        %td= deal.active
        - if deal.image.attached?
          %td= image_tag deal.image, :style => "width: 50px"

= link_to "Today Deal", root_path
= link_to "New Deal", new_deal_path

app/views/deals/new.html.haml
.row
  .col-sm-12.col-sm-offset-3
    %h1.text-center Create Deal
    = render partial: 'form'

app/views/deals/welcome.html.haml
%main
  %section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        - if @user.present?
          = render partial: "today_deal"
        - else 
          %h1.fw-light Login To See Our Deals

app/views/layouts/_header.html.haml
%nav.navbar.navbar-dark.bg-dark
  .container-fluid
    = link_to 'Flash Sales Site MVP', root_path, class: 'navbar-brand'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashSalesSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/orders/_new.html.haml
.modal-header
  %button.close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  %h3#myModalLabel READY TO THE GRAB DEAL
.modal-body
  %p To give a fair chance, only one quantity on deal will be booked
.modal-footer
  %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Close
  %button.btn.btn-light{:type => "button"}=link_to "BUY NOW", submit_orders_path, method: :post, remote: true
.error  

app/views/orders/index.html.haml
%main
  %section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        %h1.fw-light Deal Grabbed

%table.table
  %thead
    %tr
      %th{:scope => "col"} Title
      %th{:scope => "col"} Price
      %th{:scope => "col"} Discount
      %th{:scope => "col"} Image
  %tbody
    - @orders.each do |order|
      %tr
        - deal = order.order_details.first.deal
        %th{:scope => "row"}= deal.title
        %td= order.grand_total.to_f
        %td= order.discount.to_f
        - if deal.image.attached?
          %td= image_tag deal.image, :style => "width: 50px"

app/views/orders/new.js.erb
$("#myModal").find(".modal-content").html("<%= j (render 'new') %>");
$("#myModal").modal('show');

app/views/orders/submit.js.erb
location.reload();

app/views/users/show.html.haml
- if @user.present?	
	.d-flex.justify-content-center.container.mt-5
		.card.p-3.py-4
			%h5.mb-0 Login Succesful
			%span.text-black-50.p-description
				%strong= @user.name
				%br/
			%span.text-black-50.p-description
				%strong= @user.email_id
- else
	.d-flex.justify-content-center.container.mt-5
		.card.p-3.py-4
			%h5.mb-0 Login In